name: ExploreSpaceNow | SpaceNow
description:  Rocket launch tracker include SpaceX
full_description: 'An app offering a comprehensive view of the latest rocket lauch data, include SpaceX.<br>
<br>With a lot of features:
<br>- Upcoming launches.  https://testflight.apple.com/v1/invite/75d6b14aaee14884934180c97e054d5f2b8408c003a744d49bb8e9cc3184837d18f487841?ct=75HLC7G54L&advp=10000&platform=ios
<br>- Previous launches.
<br>- Extensive launch details'
android: https://telegra.ph/Replace-this-link-07-23
iOS: https://telegra.ph/Replace-this-link-07-23
web: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.jpg
  - 2.jpg
  - 4.jpg
  - 3.jpg