name: SpaceXWatch
description:  SpaceXWatch:Your Ultimate Rocket Launch Companion.
full_description: 'Discover a comprehensive view of the latest rocket launch data, including all things about SpaceX launch!<br>
<br>With a lot of features:
<br>- Stay Updated on Upcoming & Previous Launches:Never miss a launch with our up-to-date schedule.
<br>- Explore Extensive Launch Details:Dive deep into the specifics of each mission.
<br>- View Rockets in Stunning 3D:Experience rockets like never before with interactive 3D models.
<br>- Follow Upcoming & Previous Events:Stay connected with all launch events and activities.
<br>- Enjoy the Astronomy Picture of the Day:Feast your eyes on breathtaking space imagery daily.'
iOS: https://apps.apple.com/app/explorespacenow/id6698858561
screenshots:
  - 01.png
  - 02.png
  - 03.png
  - 04.png
  - 05.png